# Generated by Django 6.0.5 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_designation_customuser_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(
                choices=[
                    ('Python Developer', 'Python Developer'),
                    ('Data Analyst', 'Data Analyst'),
                    ('Testing', 'Testing'),
                    ('Research', 'Research'),
                    ('Digital Marketing', 'Digital Marketing'),
                    ('DevOps', 'DevOps'),
                    ('HR', 'HR'),
                    ('Cyber Security', 'Cyber Security'),
                    ('Engineering', 'Engineering'),
                ],
                default='Engineering',
                max_length=100,
            ),
        ),
    ]
