# Generated by Django 4.2.7 on 2026-06-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_designation_customuser_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unread_task_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
