# Generated by Django 4.2.7 on 2026-06-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='admin_file_mime_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='admin_file_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
