# Generated by Django 6.0.5 on 2026-06-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('approve_user', 'Approve User'), ('create_task', 'Create Task'), ('update_task', 'Update Task'), ('delete_task', 'Delete Task'), ('upload_file', 'Upload File'), ('approve_file', 'Approve File'), ('reject_file', 'Reject File'), ('delete_file', 'Delete File'), ('share_file', 'Share File'), ('unshare_file', 'Unshare File')], max_length=50),
        ),
    ]
