# Generated by Django 6.0.5 on 2026-06-21 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_alter_activitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('approve_user', 'Approve User'), ('reject_user', 'Reject User'), ('create_task', 'Create Task'), ('update_task', 'Update Task'), ('delete_task', 'Delete Task'), ('upload_file', 'Upload File'), ('approve_file', 'Approve File'), ('reject_file', 'Reject File'), ('delete_file', 'Delete File'), ('share_file', 'Share File'), ('unshare_file', 'Unshare File')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='activity_lo_user_id_7b8207_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='activity_lo_action_de9b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='activity_lo_created_5d03b3_idx'),
        ),
    ]
