# Generated by Django 4.2.7 on 2026-06-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0003_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('approve_user', 'Approve User'), ('reject_user', 'Reject User'), ('create_task', 'Create Task'), ('update_task', 'Update Task'), ('delete_task', 'Delete Task'), ('upload_file', 'Upload File'), ('review_file', 'Review File'), ('approve_file', 'Approve File'), ('reject_file', 'Reject File'), ('delete_file', 'Delete File'), ('share_file', 'Share File'), ('unshare_file', 'Unshare File')], max_length=50),
        ),
    ]
